#include "TM4C123.h"                    // Device header


void Timer_Init(void);

int main(void)
{
	// CONFIGURE PF1 RED LED AS OUTPUT
	SYSCTL->RCGCGPIO |= (1<<5); // ENABLE CLOCK
	GPIOF->DEN |= (1<<1); // DIGITALISE PF1
	GPIOF->DIR |= (1<<1); // SET PF1 AS OUTPUT
	
	// TIMER-1A-16BIT
	Timer_Init();
	
	while(1)
	{
	
	
	}
	
	

}

void TIMER1A_Handler()
{
	if( (TIMER1->MIS) & 0x01 )
	{
		// TOGGLE STATE OF PF1 RED LED
		GPIOF->DATA ^= (1<<1);
		// CLEAR TIMEOUT FLAG : WRITE 1 TO CLEAR
		TIMER1->ICR |= (1<<0); 	
	}

}

void Timer_Init(void)
{
	// CONFIGURING TIMER-1A-16BIT
	
	// ENABLE CLOCK FOR TIMER1
	SYSCTL->RCGCTIMER |= (1<<1); // 16/32 BIT TIMER1
	
	// DISABLE TIMER BEFORE CONFIGURATION : GPTMCTL REGISTER 
	TIMER1->CTL &= ~(1U<<0);
	
	// SELECT TIMER RESOLUTION 16/32 BIT : GPTMCFG REGISTER
	TIMER1->CFG = 0X04; // CHOOSING 16 BIT RESOLUTION
	
	// SELECT TIMER MODE: ONE SHOT/PERIODIC & UP/DOWN COUNTING
	// GPTMTAM REGISTER 
	TIMER1->TAMR = 0x02; // 0x02 PERIODIC MODE
	TIMER0->TAMR &= ~(1U<<4); // TIMER COUNTS DOWN
	
	// SET LOAD VALUE : GPTMTAIL REGISTER
	// TIMER1->TAILR = 16000; // 1ms
	// TIMER1->TAILR = 32000; // 2ms
	TIMER1->TAILR = 64000; // 4ms
	
	
	// CLEAR TIMEOUT FLAG : GPTMIC REGISTER
	// WRITE ONE TO CLEAR BIT
	TIMER1->ICR |= (1<<0);
	
	// ENABLE TIMER1A
	TIMER1->CTL |= (1<<0);
	
	// ENABLE INTERRUPT MASK FOR TIMER1A : GPTMIM REGISTER
	TIMER1->IMR |= (1<<0);
	
	// ENABLE INTERRUPT FOR TIMER1A
	NVIC->ISER[0] |= (1<<21);
	
	// WAIT FOR TIMEOUTFLAG TO SET IN INTERRUPT
	
}
